### ISSUE TITLE
Access to response and request objects

### ISSUE THREAD

**Issue by anthonator** [lincolnloop/amygdala#7]
Is it possible to get access to the response and request objects? I need access to HTTP status but I'm not seeing how.

**Comment by mikhuang** [comment]
There doesn't seem to be a way to access the request when the server sends anything with a non-20X status code. Instead of:

    deferred.reject(new Error('Request failed with status code ' + request.status));

would it make sense to do something like:

    deferred.reject({error: new Error('Request failed with status code ' + request.status), request: request});

I'm not sure how that should be handled but I really need access to the request object (thus will fork and fudge something for personal usage). Suggestions would be greatly appreciated!
